---
# Nginx
http_host: "ec2-54-170-86-104.eu-west-1.compute.amazonaws.com"
http_conf: "grimordal.conf"
http_port: "80"
https_port: "443"
ssh_port: "22"

wp_site_path: "/var/www/grimordal/"

# wp-config
wp_db_name: "defaultdb"
wp_db_user: "defaultuser"
wp_db_password: "YourPwdShouldBeLongAndSecure!"
wp_db_charset: "utf8"
wp_db_collate: "" # The Database Collate type. Don't change this if in doubt.
wp_table_prefix: "wp_"
wp_debug: false
wp_cache: true
